name: gradleCI

on:  
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        check-latest: true
    - name: Add exec permission
      run: chmod +x gradlew
    - name: Add gradle.properties files
      run: echo -e "\norg.gradle.jvmargs=-Xmx4096m\n" >> gradle.properties
    - name: Build
      run: ./gradlew build
