name: instrumentTests

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        locale:
            - "en-US"
            - "ar-SA"
            - "de-DE"
            - "el-GR"
            - "es-ES"
            - "fr-FR"
            - "hi-IN"
            - "hu-HU"
            - "hy-AM"
            - "it-IT"
            - "nl-NL"
            - "pl-PL"
            - "pt-BR"
            - "pt-PT"
            - "ro-RO"
            - "ru-RU"
            - "tr-TR"
            - "uk-UA"
            - "vi-VN"
            - "zh-CN"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '15'
            check-latest: true
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: AVD cache
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -change-locale ${{ matrix.locale }}
          disable-animations: true
          script: |
            chmod +x gradlew
            echo -e "\norg.gradle.jvmargs=-Xmx8192m\n" >> gradle.properties
            ./gradlew connectedCheck

      - name: Upload androidTests report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports-androidTests
          path: app/build/reports/androidTests/
